name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Generar animación de Snake
        uses: Platane/snk@v3
        with:
          github_user_name: TU_USUARIO
          outputs: dist/github-contribution-grid-snake.svg

      - name: Subir el resultado a la rama output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
